aws:
  region: "us-east-1"
  dynamo_table: "Carnus-xxxx"
  raw_source_s3_bucket: "carnus-raw-xxxx"
  thumbnail_s3_bucket: "carnus-thumbs-xxxx"

ingestion:
  max_workers: 16
  min_confidence: 75
  max_labels: 15
  extensions: [".cr2", ".cr3", ".arw", ".nef"]
  debug: true
  force_reprocess: false

geospatial:
  precision: 9
  bucket_size: 5

lambda_settings:
  exiftool_path: "./exiftool"
  cleanup_tmp: true
  verbose_logging: true
